version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./flight_data.py:/app/flight_data.py
      - ./flight_search.py:/app/flight_search.py
      - ./data_manager.py:/app/data_manager.py
      - ./main.py:/app/main.py
    depends_on:
      - db
  db:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Lili-2022
      MYSQL_DATABASE: flightdb
    volumes:
      - ./flightdb.sql:/docker-entrypoint-initdb.d/flightdb.sql
